// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MSGUPLINK_CALSTAR_H_
#define FLATBUFFERS_GENERATED_MSGUPLINK_CALSTAR_H_

#include "flatbuffers/flatbuffers.h"

namespace Calstar {

struct UplinkMsg;

enum UplinkType {
  UplinkType_FCOn = 0,
  UplinkType_FCOff = 1,
  UplinkType_BlackPowderOn = 2,
  UplinkType_BlackPowderOff = 3,
  UplinkType_MIN = UplinkType_FCOn,
  UplinkType_MAX = UplinkType_BlackPowderOff
};

inline const UplinkType (&EnumValuesUplinkType())[4] {
  static const UplinkType values[] = {
    UplinkType_FCOn,
    UplinkType_FCOff,
    UplinkType_BlackPowderOn,
    UplinkType_BlackPowderOff
  };
  return values;
}

inline const char * const *EnumNamesUplinkType() {
  static const char * const names[] = {
    "FCOn",
    "FCOff",
    "BlackPowderOn",
    "BlackPowderOff",
    nullptr
  };
  return names;
}

inline const char *EnumNameUplinkType(UplinkType e) {
  if (e < UplinkType_FCOn || e > UplinkType_BlackPowderOff) return "";
  const size_t index = static_cast<int>(e);
  return EnumNamesUplinkType()[index];
}

struct UplinkMsg FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_BP = 6
  };
  UplinkType Type() const {
    return static_cast<UplinkType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const flatbuffers::Vector<uint8_t> *BP() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_BP);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE) &&
           VerifyOffset(verifier, VT_BP) &&
           verifier.VerifyVector(BP()) &&
           verifier.EndTable();
  }
};

struct UplinkMsgBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_Type(UplinkType Type) {
    fbb_.AddElement<int8_t>(UplinkMsg::VT_TYPE, static_cast<int8_t>(Type), 0);
  }
  void add_BP(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> BP) {
    fbb_.AddOffset(UplinkMsg::VT_BP, BP);
  }
  explicit UplinkMsgBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  UplinkMsgBuilder &operator=(const UplinkMsgBuilder &);
  flatbuffers::Offset<UplinkMsg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<UplinkMsg>(end);
    return o;
  }
};

inline flatbuffers::Offset<UplinkMsg> CreateUplinkMsg(
    flatbuffers::FlatBufferBuilder &_fbb,
    UplinkType Type = UplinkType_FCOn,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> BP = 0) {
  UplinkMsgBuilder builder_(_fbb);
  builder_.add_BP(BP);
  builder_.add_Type(Type);
  return builder_.Finish();
}

inline flatbuffers::Offset<UplinkMsg> CreateUplinkMsgDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    UplinkType Type = UplinkType_FCOn,
    const std::vector<uint8_t> *BP = nullptr) {
  auto BP__ = BP ? _fbb.CreateVector<uint8_t>(*BP) : 0;
  return Calstar::CreateUplinkMsg(
      _fbb,
      Type,
      BP__);
}

inline const Calstar::UplinkMsg *GetUplinkMsg(const void *buf) {
  return flatbuffers::GetRoot<Calstar::UplinkMsg>(buf);
}

inline const Calstar::UplinkMsg *GetSizePrefixedUplinkMsg(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Calstar::UplinkMsg>(buf);
}

inline bool VerifyUplinkMsgBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Calstar::UplinkMsg>(nullptr);
}

inline bool VerifySizePrefixedUplinkMsgBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Calstar::UplinkMsg>(nullptr);
}

inline void FinishUplinkMsgBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Calstar::UplinkMsg> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedUplinkMsgBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Calstar::UplinkMsg> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Calstar

#endif  // FLATBUFFERS_GENERATED_MSGUPLINK_CALSTAR_H_
